name: Update Trip Status

on:
  schedule:
    - cron: '0 3 * * *'  # 매일 오전 3시 (GMT 기준)
  workflow_dispatch:     # 수동 실행도 가능

jobs:
  update-status:
    runs-on: ubuntu-latest
    steps:
      - name: Call Supabase RPC
        run: |
          curl -X POST https://uqivdagbbkdzwppzfrsx.supabase.co/rest/v1/rpc/update_trip_status \
            -H "apikey: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{}'
